name: product_list_demo
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  dio: ^5.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cached_network_image: ^3.3.1
  path_provider: ^2.1.1
  json_annotation: ^4.8.1
  connectivity_plus: ^2.3.0
  cupertino_icons: ^1.0.6
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true